// Данные слов для всех категорий (минимум 20 слов на категорию)
export const wordsData = {
  general: [
    { word: 'hello', translation: 'привет', transcription: '[həˈləʊ]' },
    { word: 'world', translation: 'мир', transcription: '[wɜːld]' },
    { word: 'good', translation: 'хороший', transcription: '[ɡʊd]' },
    { word: 'bad', translation: 'плохой', transcription: '[bæd]' },
    { word: 'big', translation: 'большой', transcription: '[bɪɡ]' },
    { word: 'small', translation: 'маленький', transcription: '[smɔːl]' },
    { word: 'new', translation: 'новый', transcription: '[njuː]' },
    { word: 'old', translation: 'старый', transcription: '[əʊld]' },
    { word: 'day', translation: 'день', transcription: '[deɪ]' },
    { word: 'night', translation: 'ночь', transcription: '[naɪt]' },
    { word: 'time', translation: 'время', transcription: '[taɪm]' },
    { word: 'way', translation: 'путь', transcription: '[weɪ]' },
    { word: 'man', translation: 'мужчина', transcription: '[mæn]' },
    { word: 'woman', translation: 'женщина', transcription: '[ˈwʊmən]' },
    { word: 'people', translation: 'люди', transcription: '[ˈpiːpl]' },
    { word: 'thing', translation: 'вещь', transcription: '[θɪŋ]' },
    { word: 'place', translation: 'место', transcription: '[pleɪs]' },
    { word: 'work', translation: 'работа', transcription: '[wɜːk]' },
    { word: 'life', translation: 'жизнь', transcription: '[laɪf]' },
    { word: 'year', translation: 'год', transcription: '[jɪə]' },
    { word: 'week', translation: 'неделя', transcription: '[wiːk]' },
    { word: 'month', translation: 'месяц', transcription: '[mʌnθ]' },
  ],
  pronouns: [
    { word: 'I', translation: 'я', transcription: '[aɪ]' },
    { word: 'you', translation: 'ты, вы', transcription: '[juː]' },
    { word: 'he', translation: 'он', transcription: '[hiː]' },
    { word: 'she', translation: 'она', transcription: '[ʃiː]' },
    { word: 'it', translation: 'оно', transcription: '[ɪt]' },
    { word: 'we', translation: 'мы', transcription: '[wiː]' },
    { word: 'they', translation: 'они', transcription: '[ðeɪ]' },
    { word: 'me', translation: 'меня, мне', transcription: '[miː]' },
    { word: 'him', translation: 'его, ему', transcription: '[hɪm]' },
    { word: 'her', translation: 'её, ей', transcription: '[hɜː]' },
    { word: 'us', translation: 'нас, нам', transcription: '[ʌs]' },
    { word: 'them', translation: 'их, им', transcription: '[ðem]' },
    { word: 'my', translation: 'мой', transcription: '[maɪ]' },
    { word: 'your', translation: 'твой, ваш', transcription: '[jɔː]' },
    { word: 'his', translation: 'его', transcription: '[hɪz]' },
    { word: 'her', translation: 'её', transcription: '[hɜː]' },
    { word: 'our', translation: 'наш', transcription: '[aʊə]' },
    { word: 'their', translation: 'их', transcription: '[ðeə]' },
    { word: 'this', translation: 'этот', transcription: '[ðɪs]' },
    { word: 'that', translation: 'тот', transcription: '[ðæt]' },
    { word: 'these', translation: 'эти', transcription: '[ðiːz]' },
    { word: 'those', translation: 'те', transcription: '[ðəʊz]' },
  ],
  body: [
    { word: 'head', translation: 'голова', transcription: '[hed]' },
    { word: 'face', translation: 'лицо', transcription: '[feɪs]' },
    { word: 'eye', translation: 'глаз', transcription: '[aɪ]' },
    { word: 'nose', translation: 'нос', transcription: '[nəʊz]' },
    { word: 'mouth', translation: 'рот', transcription: '[maʊθ]' },
    { word: 'ear', translation: 'ухо', transcription: '[ɪə]' },
    { word: 'hair', translation: 'волосы', transcription: '[heə]' },
    { word: 'neck', translation: 'шея', transcription: '[nek]' },
    { word: 'shoulder', translation: 'плечо', transcription: '[ˈʃəʊldə]' },
    { word: 'arm', translation: 'рука', transcription: '[ɑːm]' },
    { word: 'hand', translation: 'кисть', transcription: '[hænd]' },
    { word: 'finger', translation: 'палец', transcription: '[ˈfɪŋɡə]' },
    { word: 'chest', translation: 'грудь', transcription: '[tʃest]' },
    { word: 'back', translation: 'спина', transcription: '[bæk]' },
    { word: 'stomach', translation: 'живот', transcription: '[ˈstʌmək]' },
    { word: 'leg', translation: 'нога', transcription: '[leɡ]' },
    { word: 'knee', translation: 'колено', transcription: '[niː]' },
    { word: 'foot', translation: 'ступня', transcription: '[fʊt]' },
    { word: 'toe', translation: 'палец ноги', transcription: '[təʊ]' },
    { word: 'tooth', translation: 'зуб', transcription: '[tuːθ]' },
    { word: 'lip', translation: 'губа', transcription: '[lɪp]' },
    { word: 'tongue', translation: 'язык', transcription: '[tʌŋ]' },
  ],
  appearance: [
    { word: 'beautiful', translation: 'красивый', transcription: '[ˈbjuːtɪfl]' },
    { word: 'ugly', translation: 'уродливый', transcription: '[ˈʌɡli]' },
    { word: 'tall', translation: 'высокий', transcription: '[tɔːl]' },
    { word: 'short', translation: 'низкий', transcription: '[ʃɔːt]' },
    { word: 'thin', translation: 'худой', transcription: '[θɪn]' },
    { word: 'fat', translation: 'толстый', transcription: '[fæt]' },
    { word: 'young', translation: 'молодой', transcription: '[jʌŋ]' },
    { word: 'old', translation: 'старый', transcription: '[əʊld]' },
    { word: 'handsome', translation: 'красивый (о мужчине)', transcription: '[ˈhænsəm]' },
    { word: 'pretty', translation: 'милый', transcription: '[ˈprɪti]' },
    { word: 'slim', translation: 'стройный', transcription: '[slɪm]' },
    { word: 'muscular', translation: 'мускулистый', transcription: '[ˈmʌskjələ]' },
    { word: 'curly', translation: 'кудрявый', transcription: '[ˈkɜːli]' },
    { word: 'straight', translation: 'прямой', transcription: '[streɪt]' },
    { word: 'blonde', translation: 'блондин', transcription: '[blɒnd]' },
    { word: 'brunette', translation: 'брюнет', transcription: '[bruːˈnet]' },
    { word: 'bald', translation: 'лысый', transcription: '[bɔːld]' },
    { word: 'beard', translation: 'борода', transcription: '[bɪəd]' },
    { word: 'mustache', translation: 'усы', transcription: '[məˈstɑːʃ]' },
    { word: 'glasses', translation: 'очки', transcription: '[ˈɡlɑːsɪz]' },
    { word: 'attractive', translation: 'привлекательный', transcription: '[əˈtræktɪv]' },
    { word: 'elegant', translation: 'элегантный', transcription: '[ˈelɪɡənt]' },
  ],
  character: [
    { word: 'kind', translation: 'добрый', transcription: '[kaɪnd]' },
    { word: 'mean', translation: 'злой', transcription: '[miːn]' },
    { word: 'friendly', translation: 'дружелюбный', transcription: '[ˈfrendli]' },
    { word: 'shy', translation: 'застенчивый', transcription: '[ʃaɪ]' },
    { word: 'confident', translation: 'уверенный', transcription: '[ˈkɒnfɪdənt]' },
    { word: 'brave', translation: 'храбрый', transcription: '[breɪv]' },
    { word: 'afraid', translation: 'испуганный', transcription: '[əˈfreɪd]' },
    { word: 'happy', translation: 'счастливый', transcription: '[ˈhæpi]' },
    { word: 'sad', translation: 'грустный', transcription: '[sæd]' },
    { word: 'angry', translation: 'злой', transcription: '[ˈæŋɡri]' },
    { word: 'excited', translation: 'взволнованный', transcription: '[ɪkˈsaɪtɪd]' },
    { word: 'calm', translation: 'спокойный', transcription: '[kɑːm]' },
    { word: 'nervous', translation: 'нервный', transcription: '[ˈnɜːvəs]' },
    { word: 'cheerful', translation: 'весёлый', transcription: '[ˈtʃɪəfl]' },
    { word: 'serious', translation: 'серьёзный', transcription: '[ˈsɪəriəs]' },
    { word: 'funny', translation: 'смешной', transcription: '[ˈfʌni]' },
    { word: 'smart', translation: 'умный', transcription: '[smɑːt]' },
    { word: 'stupid', translation: 'глупый', transcription: '[ˈstjuːpɪd]' },
    { word: 'honest', translation: 'честный', transcription: '[ˈɒnɪst]' },
    { word: 'generous', translation: 'щедрый', transcription: '[ˈdʒenərəs]' },
    { word: 'selfish', translation: 'эгоистичный', transcription: '[ˈselfɪʃ]' },
    { word: 'patient', translation: 'терпеливый', transcription: '[ˈpeɪʃənt]' },
  ],
  family: [
    { word: 'family', translation: 'семья', transcription: '[ˈfæməli]' },
    { word: 'father', translation: 'отец', transcription: '[ˈfɑːðə]' },
    { word: 'mother', translation: 'мать', transcription: '[ˈmʌðə]' },
    { word: 'son', translation: 'сын', transcription: '[sʌn]' },
    { word: 'daughter', translation: 'дочь', transcription: '[ˈdɔːtə]' },
    { word: 'brother', translation: 'брат', transcription: '[ˈbrʌðə]' },
    { word: 'sister', translation: 'сестра', transcription: '[ˈsɪstə]' },
    { word: 'grandfather', translation: 'дедушка', transcription: '[ˈɡrænfɑːðə]' },
    { word: 'grandmother', translation: 'бабушка', transcription: '[ˈɡrænmʌðə]' },
    { word: 'uncle', translation: 'дядя', transcription: '[ˈʌŋkl]' },
    { word: 'aunt', translation: 'тётя', transcription: '[ɑːnt]' },
    { word: 'cousin', translation: 'двоюродный брат/сестра', transcription: '[ˈkʌzn]' },
    { word: 'husband', translation: 'муж', transcription: '[ˈhʌzbənd]' },
    { word: 'wife', translation: 'жена', transcription: '[waɪf]' },
    { word: 'parent', translation: 'родитель', transcription: '[ˈpeərənt]' },
    { word: 'child', translation: 'ребёнок', transcription: '[tʃaɪld]' },
    { word: 'baby', translation: 'младенец', transcription: '[ˈbeɪbi]' },
    { word: 'twin', translation: 'близнец', transcription: '[twɪn]' },
    { word: 'nephew', translation: 'племянник', transcription: '[ˈnefjuː]' },
    { word: 'niece', translation: 'племянница', transcription: '[niːs]' },
    { word: 'relative', translation: 'родственник', transcription: '[ˈrelətɪv]' },
    { word: 'friend', translation: 'друг', transcription: '[frend]' },
  ],
  clothing: [
    { word: 'shirt', translation: 'рубашка', transcription: '[ʃɜːt]' },
    { word: 'pants', translation: 'брюки', transcription: '[pænts]' },
    { word: 'dress', translation: 'платье', transcription: '[dres]' },
    { word: 'skirt', translation: 'юбка', transcription: '[skɜːt]' },
    { word: 'jacket', translation: 'куртка', transcription: '[ˈdʒækɪt]' },
    { word: 'coat', translation: 'пальто', transcription: '[kəʊt]' },
    { word: 'hat', translation: 'шляпа', transcription: '[hæt]' },
    { word: 'shoes', translation: 'туфли', transcription: '[ʃuːz]' },
    { word: 'boots', translation: 'сапоги', transcription: '[buːts]' },
    { word: 'sneakers', translation: 'кроссовки', transcription: '[ˈsniːkəz]' },
    { word: 'socks', translation: 'носки', transcription: '[sɒks]' },
    { word: 'tie', translation: 'галстук', transcription: '[taɪ]' },
    { word: 'belt', translation: 'ремень', transcription: '[belt]' },
    { word: 'gloves', translation: 'перчатки', transcription: '[ɡlʌvz]' },
    { word: 'scarf', translation: 'шарф', transcription: '[skɑːf]' },
    { word: 'cap', translation: 'кепка', transcription: '[kæp]' },
    { word: 'sweater', translation: 'свитер', transcription: '[ˈswetə]' },
    { word: 'jeans', translation: 'джинсы', transcription: '[dʒiːnz]' },
    { word: 'shorts', translation: 'шорты', transcription: '[ʃɔːts]' },
    { word: 'underwear', translation: 'нижнее бельё', transcription: '[ˈʌndəweə]' },
    { word: 'suit', translation: 'костюм', transcription: '[suːt]' },
    { word: 'uniform', translation: 'униформа', transcription: '[ˈjuːnɪfɔːm]' },
  ],
  life: [
    { word: 'birth', translation: 'рождение', transcription: '[bɜːθ]' },
    { word: 'death', translation: 'смерть', transcription: '[deθ]' },
    { word: 'marriage', translation: 'брак', transcription: '[ˈmærɪdʒ]' },
    { word: 'divorce', translation: 'развод', transcription: '[dɪˈvɔːs]' },
    { word: 'wedding', translation: 'свадьба', transcription: '[ˈwedɪŋ]' },
    { word: 'funeral', translation: 'похороны', transcription: '[ˈfjuːnərəl]' },
    { word: 'birthday', translation: 'день рождения', transcription: '[ˈbɜːθdeɪ]' },
    { word: 'anniversary', translation: 'годовщина', transcription: '[ˌænɪˈvɜːsəri]' },
    { word: 'childhood', translation: 'детство', transcription: '[ˈtʃaɪldhʊd]' },
    { word: 'youth', translation: 'юность', transcription: '[juːθ]' },
    { word: 'adulthood', translation: 'взрослость', transcription: '[ˈædʌlthʊd]' },
    { word: 'old age', translation: 'старость', transcription: '[əʊld eɪdʒ]' },
    { word: 'health', translation: 'здоровье', transcription: '[helθ]' },
    { word: 'illness', translation: 'болезнь', transcription: '[ˈɪlnəs]' },
    { word: 'happiness', translation: 'счастье', transcription: '[ˈhæpinəs]' },
    { word: 'sadness', translation: 'грусть', transcription: '[ˈsædnəs]' },
    { word: 'love', translation: 'любовь', transcription: '[lʌv]' },
    { word: 'hate', translation: 'ненависть', transcription: '[heɪt]' },
    { word: 'hope', translation: 'надежда', transcription: '[həʊp]' },
    { word: 'dream', translation: 'мечта', transcription: '[driːm]' },
    { word: 'goal', translation: 'цель', transcription: '[ɡəʊl]' },
    { word: 'success', translation: 'успех', transcription: '[səkˈses]' },
  ],
  food: [
    { word: 'bread', translation: 'хлеб', transcription: '[bred]' },
    { word: 'butter', translation: 'масло', transcription: '[ˈbʌtə]' },
    { word: 'cheese', translation: 'сыр', transcription: '[tʃiːz]' },
    { word: 'milk', translation: 'молоко', transcription: '[mɪlk]' },
    { word: 'egg', translation: 'яйцо', transcription: '[eɡ]' },
    { word: 'meat', translation: 'мясо', transcription: '[miːt]' },
    { word: 'fish', translation: 'рыба', transcription: '[fɪʃ]' },
    { word: 'chicken', translation: 'курица', transcription: '[ˈtʃɪkɪn]' },
    { word: 'rice', translation: 'рис', transcription: '[raɪs]' },
    { word: 'pasta', translation: 'макароны', transcription: '[ˈpæstə]' },
    { word: 'potato', translation: 'картофель', transcription: '[pəˈteɪtəʊ]' },
    { word: 'tomato', translation: 'помидор', transcription: '[təˈmɑːtəʊ]' },
    { word: 'apple', translation: 'яблоко', transcription: '[ˈæpl]' },
    { word: 'banana', translation: 'банан', transcription: '[bəˈnɑːnə]' },
    { word: 'orange', translation: 'апельсин', transcription: '[ˈɒrɪndʒ]' },
    { word: 'water', translation: 'вода', transcription: '[ˈwɔːtə]' },
    { word: 'coffee', translation: 'кофе', transcription: '[ˈkɒfi]' },
    { word: 'tea', translation: 'чай', transcription: '[tiː]' },
    { word: 'juice', translation: 'сок', transcription: '[dʒuːs]' },
    { word: 'soup', translation: 'суп', transcription: '[suːp]' },
    { word: 'salad', translation: 'салат', transcription: '[ˈsæləd]' },
    { word: 'cake', translation: 'торт', transcription: '[keɪk]' },
  ],
  professions: [
    { word: 'teacher', translation: 'учитель', transcription: '[ˈtiːtʃə]' },
    { word: 'doctor', translation: 'врач', transcription: '[ˈdɒktə]' },
    { word: 'nurse', translation: 'медсестра', transcription: '[nɜːs]' },
    { word: 'engineer', translation: 'инженер', transcription: '[ˌendʒɪˈnɪə]' },
    { word: 'lawyer', translation: 'адвокат', transcription: '[ˈlɔːjə]' },
    { word: 'pilot', translation: 'пилот', transcription: '[ˈpaɪlət]' },
    { word: 'chef', translation: 'повар', transcription: '[ʃef]' },
    { word: 'waiter', translation: 'официант', transcription: '[ˈweɪtə]' },
    { word: 'driver', translation: 'водитель', transcription: '[ˈdraɪvə]' },
    { word: 'police', translation: 'полиция', transcription: '[pəˈliːs]' },
    { word: 'firefighter', translation: 'пожарный', transcription: '[ˈfaɪəfaɪtə]' },
    { word: 'soldier', translation: 'солдат', transcription: '[ˈsəʊldʒə]' },
    { word: 'artist', translation: 'художник', transcription: '[ˈɑːtɪst]' },
    { word: 'musician', translation: 'музыкант', transcription: '[mjuˈzɪʃən]' },
    { word: 'actor', translation: 'актёр', transcription: '[ˈæktə]' },
    { word: 'writer', translation: 'писатель', transcription: '[ˈraɪtə]' },
    { word: 'journalist', translation: 'журналист', transcription: '[ˈdʒɜːnəlɪst]' },
    { word: 'businessman', translation: 'бизнесмен', transcription: '[ˈbɪznəsmæn]' },
    { word: 'manager', translation: 'менеджер', transcription: '[ˈmænɪdʒə]' },
    { word: 'secretary', translation: 'секретарь', transcription: '[ˈsekrətri]' },
    { word: 'accountant', translation: 'бухгалтер', transcription: '[əˈkaʊntənt]' },
    { word: 'architect', translation: 'архитектор', transcription: '[ˈɑːkɪtekt]' },
  ],
  home: [
    { word: 'house', translation: 'дом', transcription: '[haʊs]' },
    { word: 'room', translation: 'комната', transcription: '[ruːm]' },
    { word: 'kitchen', translation: 'кухня', transcription: '[ˈkɪtʃɪn]' },
    { word: 'bedroom', translation: 'спальня', transcription: '[ˈbedruːm]' },
    { word: 'bathroom', translation: 'ванная', transcription: '[ˈbɑːθruːm]' },
    { word: 'living room', translation: 'гостиная', transcription: '[ˈlɪvɪŋ ruːm]' },
    { word: 'door', translation: 'дверь', transcription: '[dɔː]' },
    { word: 'window', translation: 'окно', transcription: '[ˈwɪndəʊ]' },
    { word: 'wall', translation: 'стена', transcription: '[wɔːl]' },
    { word: 'floor', translation: 'пол', transcription: '[flɔː]' },
    { word: 'ceiling', translation: 'потолок', transcription: '[ˈsiːlɪŋ]' },
    { word: 'roof', translation: 'крыша', transcription: '[ruːf]' },
    { word: 'table', translation: 'стол', transcription: '[ˈteɪbl]' },
    { word: 'chair', translation: 'стул', transcription: '[tʃeə]' },
    { word: 'bed', translation: 'кровать', transcription: '[bed]' },
    { word: 'sofa', translation: 'диван', transcription: '[ˈsəʊfə]' },
    { word: 'lamp', translation: 'лампа', transcription: '[læmp]' },
    { word: 'mirror', translation: 'зеркало', transcription: '[ˈmɪrə]' },
    { word: 'clock', translation: 'часы', transcription: '[klɒk]' },
    { word: 'refrigerator', translation: 'холодильник', transcription: '[rɪˈfrɪdʒəreɪtə]' },
    { word: 'oven', translation: 'духовка', transcription: '[ˈʌvn]' },
    { word: 'sink', translation: 'раковина', transcription: '[sɪŋk]' },
  ],
  sports: [
    { word: 'football', translation: 'футбол', transcription: '[ˈfʊtbɔːl]' },
    { word: 'basketball', translation: 'баскетбол', transcription: '[ˈbɑːskɪtbɔːl]' },
    { word: 'tennis', translation: 'теннис', transcription: '[ˈtenɪs]' },
    { word: 'swimming', translation: 'плавание', transcription: '[ˈswɪmɪŋ]' },
    { word: 'running', translation: 'бег', transcription: '[ˈrʌnɪŋ]' },
    { word: 'cycling', translation: 'велоспорт', transcription: '[ˈsaɪklɪŋ]' },
    { word: 'golf', translation: 'гольф', transcription: '[ɡɒlf]' },
    { word: 'volleyball', translation: 'волейбол', transcription: '[ˈvɒlibɔːl]' },
    { word: 'hockey', translation: 'хоккей', transcription: '[ˈhɒki]' },
    { word: 'boxing', translation: 'бокс', transcription: '[ˈbɒksɪŋ]' },
    { word: 'yoga', translation: 'йога', transcription: '[ˈjəʊɡə]' },
    { word: 'gym', translation: 'спортзал', transcription: '[dʒɪm]' },
    { word: 'exercise', translation: 'упражнение', transcription: '[ˈeksəsaɪz]' },
    { word: 'training', translation: 'тренировка', transcription: '[ˈtreɪnɪŋ]' },
    { word: 'match', translation: 'матч', transcription: '[mætʃ]' },
    { word: 'team', translation: 'команда', transcription: '[tiːm]' },
    { word: 'player', translation: 'игрок', transcription: '[ˈpleɪə]' },
    { word: 'coach', translation: 'тренер', transcription: '[kəʊtʃ]' },
    { word: 'stadium', translation: 'стадион', transcription: '[ˈsteɪdiəm]' },
    { word: 'ball', translation: 'мяч', transcription: '[bɔːl]' },
    { word: 'goal', translation: 'гол', transcription: '[ɡəʊl]' },
    { word: 'victory', translation: 'победа', transcription: '[ˈvɪktəri]' },
  ],
  travel: [
    { word: 'trip', translation: 'поездка', transcription: '[trɪp]' },
    { word: 'journey', translation: 'путешествие', transcription: '[ˈdʒɜːni]' },
    { word: 'vacation', translation: 'отпуск', transcription: '[vəˈkeɪʃən]' },
    { word: 'hotel', translation: 'отель', transcription: '[həʊˈtel]' },
    { word: 'airport', translation: 'аэропорт', transcription: '[ˈeəpɔːt]' },
    { word: 'plane', translation: 'самолёт', transcription: '[pleɪn]' },
    { word: 'train', translation: 'поезд', transcription: '[treɪn]' },
    { word: 'bus', translation: 'автобус', transcription: '[bʌs]' },
    { word: 'car', translation: 'машина', transcription: '[kɑː]' },
    { word: 'taxi', translation: 'такси', transcription: '[ˈtæksi]' },
    { word: 'ticket', translation: 'билет', transcription: '[ˈtɪkɪt]' },
    { word: 'passport', translation: 'паспорт', transcription: '[ˈpɑːspɔːt]' },
    { word: 'luggage', translation: 'багаж', transcription: '[ˈlʌɡɪdʒ]' },
    { word: 'suitcase', translation: 'чемодан', transcription: '[ˈsuːtkeɪs]' },
    { word: 'map', translation: 'карта', transcription: '[mæp]' },
    { word: 'beach', translation: 'пляж', transcription: '[biːtʃ]' },
    { word: 'mountain', translation: 'гора', transcription: '[ˈmaʊntɪn]' },
    { word: 'city', translation: 'город', transcription: '[ˈsɪti]' },
    { word: 'country', translation: 'страна', transcription: '[ˈkʌntri]' },
    { word: 'tourist', translation: 'турист', transcription: '[ˈtʊərɪst]' },
    { word: 'guide', translation: 'гид', transcription: '[ɡaɪd]' },
    { word: 'sightseeing', translation: 'осмотр достопримечательностей', transcription: '[ˈsaɪtsiːɪŋ]' },
  ],
  qualities: [
    { word: 'heavy', translation: 'тяжёлый', transcription: '[ˈhevi]' },
    { word: 'light', translation: 'лёгкий', transcription: '[laɪt]' },
    { word: 'hard', translation: 'твёрдый', transcription: '[hɑːd]' },
    { word: 'soft', translation: 'мягкий', transcription: '[sɒft]' },
    { word: 'smooth', translation: 'гладкий', transcription: '[smuːð]' },
    { word: 'rough', translation: 'шероховатый', transcription: '[rʌf]' },
    { word: 'sharp', translation: 'острый', transcription: '[ʃɑːp]' },
    { word: 'dull', translation: 'тупой', transcription: '[dʌl]' },
    { word: 'clean', translation: 'чистый', transcription: '[kliːn]' },
    { word: 'dirty', translation: 'грязный', transcription: '[ˈdɜːti]' },
    { word: 'wet', translation: 'мокрый', transcription: '[wet]' },
    { word: 'dry', translation: 'сухой', transcription: '[draɪ]' },
    { word: 'hot', translation: 'горячий', transcription: '[hɒt]' },
    { word: 'cold', translation: 'холодный', transcription: '[kəʊld]' },
    { word: 'warm', translation: 'тёплый', transcription: '[wɔːm]' },
    { word: 'cool', translation: 'прохладный', transcription: '[kuːl]' },
    { word: 'fresh', translation: 'свежий', transcription: '[freʃ]' },
    { word: 'stale', translation: 'несвежий', transcription: '[steɪl]' },
    { word: 'new', translation: 'новый', transcription: '[njuː]' },
    { word: 'old', translation: 'старый', transcription: '[əʊld]' },
    { word: 'modern', translation: 'современный', transcription: '[ˈmɒdn]' },
    { word: 'ancient', translation: 'древний', transcription: '[ˈeɪnʃənt]' },
  ],
  colors: [
    { word: 'red', translation: 'красный', transcription: '[red]' },
    { word: 'blue', translation: 'синий', transcription: '[bluː]' },
    { word: 'green', translation: 'зелёный', transcription: '[ɡriːn]' },
    { word: 'yellow', translation: 'жёлтый', transcription: '[ˈjeləʊ]' },
    { word: 'orange', translation: 'оранжевый', transcription: '[ˈɒrɪndʒ]' },
    { word: 'purple', translation: 'фиолетовый', transcription: '[ˈpɜːpl]' },
    { word: 'pink', translation: 'розовый', transcription: '[pɪŋk]' },
    { word: 'brown', translation: 'коричневый', transcription: '[braʊn]' },
    { word: 'black', translation: 'чёрный', transcription: '[blæk]' },
    { word: 'white', translation: 'белый', transcription: '[waɪt]' },
    { word: 'gray', translation: 'серый', transcription: '[ɡreɪ]' },
    { word: 'gold', translation: 'золотой', transcription: '[ɡəʊld]' },
    { word: 'silver', translation: 'серебряный', transcription: '[ˈsɪlvə]' },
    { word: 'beige', translation: 'бежевый', transcription: '[beɪʒ]' },
    { word: 'navy', translation: 'тёмно-синий', transcription: '[ˈneɪvi]' },
    { word: 'turquoise', translation: 'бирюзовый', transcription: '[ˈtɜːkwɔɪz]' },
    { word: 'lime', translation: 'лаймовый', transcription: '[laɪm]' },
    { word: 'maroon', translation: 'тёмно-красный', transcription: '[məˈruːn]' },
    { word: 'violet', translation: 'фиолетовый', transcription: '[ˈvaɪələt]' },
    { word: 'indigo', translation: 'индиго', transcription: '[ˈɪndɪɡəʊ]' },
    { word: 'crimson', translation: 'малиновый', transcription: '[ˈkrɪmzn]' },
    { word: 'amber', translation: 'янтарный', transcription: '[ˈæmbə]' },
  ],
  properties: [
    { word: 'fast', translation: 'быстрый', transcription: '[fɑːst]' },
    { word: 'slow', translation: 'медленный', transcription: '[sləʊ]' },
    { word: 'quick', translation: 'быстрый', transcription: '[kwɪk]' },
    { word: 'rapid', translation: 'стремительный', transcription: '[ˈræpɪd]' },
    { word: 'loud', translation: 'громкий', transcription: '[laʊd]' },
    { word: 'quiet', translation: 'тихий', transcription: '[ˈkwaɪət]' },
    { word: 'silent', translation: 'бесшумный', transcription: '[ˈsaɪlənt]' },
    { word: 'bright', translation: 'яркий', transcription: '[braɪt]' },
    { word: 'dark', translation: 'тёмный', transcription: '[dɑːk]' },
    { word: 'wide', translation: 'широкий', transcription: '[waɪd]' },
    { word: 'narrow', translation: 'узкий', transcription: '[ˈnærəʊ]' },
    { word: 'thick', translation: 'толстый', transcription: '[θɪk]' },
    { word: 'thin', translation: 'тонкий', transcription: '[θɪn]' },
    { word: 'long', translation: 'длинный', transcription: '[lɒŋ]' },
    { word: 'short', translation: 'короткий', transcription: '[ʃɔːt]' },
    { word: 'high', translation: 'высокий', transcription: '[haɪ]' },
    { word: 'low', translation: 'низкий', transcription: '[ləʊ]' },
    { word: 'deep', translation: 'глубокий', transcription: '[diːp]' },
    { word: 'shallow', translation: 'мелкий', transcription: '[ˈʃæləʊ]' },
    { word: 'strong', translation: 'сильный', transcription: '[strɒŋ]' },
    { word: 'weak', translation: 'слабый', transcription: '[wiːk]' },
    { word: 'powerful', translation: 'мощный', transcription: '[ˈpaʊəfl]' },
  ],
  time: [
    { word: 'time', translation: 'время', transcription: '[taɪm]' },
    { word: 'hour', translation: 'час', transcription: '[aʊə]' },
    { word: 'minute', translation: 'минута', transcription: '[ˈmɪnɪt]' },
    { word: 'second', translation: 'секунда', transcription: '[ˈsekənd]' },
    { word: 'day', translation: 'день', transcription: '[deɪ]' },
    { word: 'week', translation: 'неделя', transcription: '[wiːk]' },
    { word: 'month', translation: 'месяц', transcription: '[mʌnθ]' },
    { word: 'year', translation: 'год', transcription: '[jɪə]' },
    { word: 'morning', translation: 'утро', transcription: '[ˈmɔːnɪŋ]' },
    { word: 'afternoon', translation: 'день', transcription: '[ˌɑːftəˈnuːn]' },
    { word: 'evening', translation: 'вечер', transcription: '[ˈiːvnɪŋ]' },
    { word: 'night', translation: 'ночь', transcription: '[naɪt]' },
    { word: 'today', translation: 'сегодня', transcription: '[təˈdeɪ]' },
    { word: 'yesterday', translation: 'вчера', transcription: '[ˈjestədeɪ]' },
    { word: 'tomorrow', translation: 'завтра', transcription: '[təˈmɒrəʊ]' },
    { word: 'now', translation: 'сейчас', transcription: '[naʊ]' },
    { word: 'then', translation: 'тогда', transcription: '[ðen]' },
    { word: 'before', translation: 'до', transcription: '[bɪˈfɔː]' },
    { word: 'after', translation: 'после', transcription: '[ˈɑːftə]' },
    { word: 'early', translation: 'рано', transcription: '[ˈɜːli]' },
    { word: 'late', translation: 'поздно', transcription: '[leɪt]' },
    { word: 'soon', translation: 'скоро', transcription: '[suːn]' },
  ],
  cardinal: [
    { word: 'zero', translation: 'ноль', transcription: '[ˈzɪərəʊ]' },
    { word: 'one', translation: 'один', transcription: '[wʌn]' },
    { word: 'two', translation: 'два', transcription: '[tuː]' },
    { word: 'three', translation: 'три', transcription: '[θriː]' },
    { word: 'four', translation: 'четыре', transcription: '[fɔː]' },
    { word: 'five', translation: 'пять', transcription: '[faɪv]' },
    { word: 'six', translation: 'шесть', transcription: '[sɪks]' },
    { word: 'seven', translation: 'семь', transcription: '[ˈsevn]' },
    { word: 'eight', translation: 'восемь', transcription: '[eɪt]' },
    { word: 'nine', translation: 'девять', transcription: '[naɪn]' },
    { word: 'ten', translation: 'десять', transcription: '[ten]' },
    { word: 'eleven', translation: 'одиннадцать', transcription: '[ɪˈlevn]' },
    { word: 'twelve', translation: 'двенадцать', transcription: '[twelv]' },
    { word: 'thirteen', translation: 'тринадцать', transcription: '[ˌθɜːˈtiːn]' },
    { word: 'fourteen', translation: 'четырнадцать', transcription: '[ˌfɔːˈtiːn]' },
    { word: 'fifteen', translation: 'пятнадцать', transcription: '[ˌfɪfˈtiːn]' },
    { word: 'sixteen', translation: 'шестнадцать', transcription: '[ˌsɪksˈtiːn]' },
    { word: 'seventeen', translation: 'семнадцать', transcription: '[ˌsevnˈtiːn]' },
    { word: 'eighteen', translation: 'восемнадцать', transcription: '[ˌeɪˈtiːn]' },
    { word: 'nineteen', translation: 'девятнадцать', transcription: '[ˌnaɪnˈtiːn]' },
    { word: 'twenty', translation: 'двадцать', transcription: '[ˈtwenti]' },
    { word: 'hundred', translation: 'сто', transcription: '[ˈhʌndrəd]' },
  ],
  ordinal: [
    { word: 'first', translation: 'первый', transcription: '[fɜːst]' },
    { word: 'second', translation: 'второй', transcription: '[ˈsekənd]' },
    { word: 'third', translation: 'третий', transcription: '[θɜːd]' },
    { word: 'fourth', translation: 'четвёртый', transcription: '[fɔːθ]' },
    { word: 'fifth', translation: 'пятый', transcription: '[fɪfθ]' },
    { word: 'sixth', translation: 'шестой', transcription: '[sɪksθ]' },
    { word: 'seventh', translation: 'седьмой', transcription: '[ˈsevnθ]' },
    { word: 'eighth', translation: 'восьмой', transcription: '[eɪtθ]' },
    { word: 'ninth', translation: 'девятый', transcription: '[naɪnθ]' },
    { word: 'tenth', translation: 'десятый', transcription: '[tenθ]' },
    { word: 'eleventh', translation: 'одиннадцатый', transcription: '[ɪˈlevnθ]' },
    { word: 'twelfth', translation: 'двенадцатый', transcription: '[twelfθ]' },
    { word: 'thirteenth', translation: 'тринадцатый', transcription: '[ˌθɜːˈtiːnθ]' },
    { word: 'fourteenth', translation: 'четырнадцатый', transcription: '[ˌfɔːˈtiːnθ]' },
    { word: 'fifteenth', translation: 'пятнадцатый', transcription: '[ˌfɪfˈtiːnθ]' },
    { word: 'sixteenth', translation: 'шестнадцатый', transcription: '[ˌsɪksˈtiːnθ]' },
    { word: 'seventeenth', translation: 'семнадцатый', transcription: '[ˌsevnˈtiːnθ]' },
    { word: 'eighteenth', translation: 'восемнадцатый', transcription: '[ˌeɪˈtiːnθ]' },
    { word: 'nineteenth', translation: 'девятнадцатый', transcription: '[ˌnaɪnˈtiːnθ]' },
    { word: 'twentieth', translation: 'двадцатый', transcription: '[ˈtwentiəθ]' },
    { word: 'last', translation: 'последний', transcription: '[lɑːst]' },
    { word: 'next', translation: 'следующий', transcription: '[nekst]' },
  ],
  weather: [
    { word: 'weather', translation: 'погода', transcription: '[ˈweðə]' },
    { word: 'sun', translation: 'солнце', transcription: '[sʌn]' },
    { word: 'rain', translation: 'дождь', transcription: '[reɪn]' },
    { word: 'snow', translation: 'снег', transcription: '[snəʊ]' },
    { word: 'wind', translation: 'ветер', transcription: '[wɪnd]' },
    { word: 'cloud', translation: 'облако', transcription: '[klaʊd]' },
    { word: 'storm', translation: 'шторм', transcription: '[stɔːm]' },
    { word: 'fog', translation: 'туман', transcription: '[fɒɡ]' },
    { word: 'thunder', translation: 'гром', transcription: '[ˈθʌndə]' },
    { word: 'lightning', translation: 'молния', transcription: '[ˈlaɪtnɪŋ]' },
    { word: 'sunny', translation: 'солнечный', transcription: '[ˈsʌni]' },
    { word: 'rainy', translation: 'дождливый', transcription: '[ˈreɪni]' },
    { word: 'cloudy', translation: 'облачный', transcription: '[ˈklaʊdi]' },
    { word: 'windy', translation: 'ветреный', transcription: '[ˈwɪndi]' },
    { word: 'snowy', translation: 'снежный', transcription: '[ˈsnəʊi]' },
    { word: 'foggy', translation: 'туманный', transcription: '[ˈfɒɡi]' },
    { word: 'hot', translation: 'жаркий', transcription: '[hɒt]' },
    { word: 'cold', translation: 'холодный', transcription: '[kəʊld]' },
    { word: 'warm', translation: 'тёплый', transcription: '[wɔːm]' },
    { word: 'cool', translation: 'прохладный', transcription: '[kuːl]' },
    { word: 'temperature', translation: 'температура', transcription: '[ˈtemprətʃə]' },
    { word: 'forecast', translation: 'прогноз', transcription: '[ˈfɔːkɑːst]' },
  ],
  landscape: [
    { word: 'mountain', translation: 'гора', transcription: '[ˈmaʊntɪn]' },
    { word: 'hill', translation: 'холм', transcription: '[hɪl]' },
    { word: 'valley', translation: 'долина', transcription: '[ˈvæli]' },
    { word: 'river', translation: 'река', transcription: '[ˈrɪvə]' },
    { word: 'lake', translation: 'озеро', transcription: '[leɪk]' },
    { word: 'ocean', translation: 'океан', transcription: '[ˈəʊʃən]' },
    { word: 'sea', translation: 'море', transcription: '[siː]' },
    { word: 'beach', translation: 'пляж', transcription: '[biːtʃ]' },
    { word: 'forest', translation: 'лес', transcription: '[ˈfɒrɪst]' },
    { word: 'field', translation: 'поле', transcription: '[fiːld]' },
    { word: 'desert', translation: 'пустыня', transcription: '[ˈdezət]' },
    { word: 'island', translation: 'остров', transcription: '[ˈaɪlənd]' },
    { word: 'coast', translation: 'побережье', transcription: '[kəʊst]' },
    { word: 'shore', translation: 'берег', transcription: '[ʃɔː]' },
    { word: 'cliff', translation: 'утес', transcription: '[klɪf]' },
    { word: 'cave', translation: 'пещера', transcription: '[keɪv]' },
    { word: 'waterfall', translation: 'водопад', transcription: '[ˈwɔːtəfɔːl]' },
    { word: 'meadow', translation: 'луг', transcription: '[ˈmedəʊ]' },
    { word: 'plain', translation: 'равнина', transcription: '[pleɪn]' },
    { word: 'volcano', translation: 'вулкан', transcription: '[vɒlˈkeɪnəʊ]' },
    { word: 'canyon', translation: 'каньон', transcription: '[ˈkænjən]' },
    { word: 'glacier', translation: 'ледник', transcription: '[ˈɡlæsiə]' },
  ],
  animals: [
    { word: 'dog', translation: 'собака', transcription: '[dɒɡ]' },
    { word: 'cat', translation: 'кот', transcription: '[kæt]' },
    { word: 'bird', translation: 'птица', transcription: '[bɜːd]' },
    { word: 'fish', translation: 'рыба', transcription: '[fɪʃ]' },
    { word: 'horse', translation: 'лошадь', transcription: '[hɔːs]' },
    { word: 'cow', translation: 'корова', transcription: '[kaʊ]' },
    { word: 'pig', translation: 'свинья', transcription: '[pɪɡ]' },
    { word: 'sheep', translation: 'овца', transcription: '[ʃiːp]' },
    { word: 'goat', translation: 'коза', transcription: '[ɡəʊt]' },
    { word: 'chicken', translation: 'курица', transcription: '[ˈtʃɪkɪn]' },
    { word: 'duck', translation: 'утка', transcription: '[dʌk]' },
    { word: 'rabbit', translation: 'кролик', transcription: '[ˈræbɪt]' },
    { word: 'mouse', translation: 'мышь', transcription: '[maʊs]' },
    { word: 'lion', translation: 'лев', transcription: '[ˈlaɪən]' },
    { word: 'tiger', translation: 'тигр', transcription: '[ˈtaɪɡə]' },
    { word: 'bear', translation: 'медведь', transcription: '[beə]' },
    { word: 'wolf', translation: 'волк', transcription: '[wʊlf]' },
    { word: 'elephant', translation: 'слон', transcription: '[ˈelɪfənt]' },
    { word: 'monkey', translation: 'обезьяна', transcription: '[ˈmʌŋki]' },
    { word: 'snake', translation: 'змея', transcription: '[sneɪk]' },
    { word: 'spider', translation: 'паук', transcription: '[ˈspaɪdə]' },
    { word: 'butterfly', translation: 'бабочка', transcription: '[ˈbʌtəflaɪ]' },
  ],
  plants: [
    { word: 'tree', translation: 'дерево', transcription: '[triː]' },
    { word: 'flower', translation: 'цветок', transcription: '[ˈflaʊə]' },
    { word: 'grass', translation: 'трава', transcription: '[ɡrɑːs]' },
    { word: 'leaf', translation: 'лист', transcription: '[liːf]' },
    { word: 'branch', translation: 'ветка', transcription: '[brɑːntʃ]' },
    { word: 'root', translation: 'корень', transcription: '[ruːt]' },
    { word: 'seed', translation: 'семя', transcription: '[siːd]' },
    { word: 'fruit', translation: 'фрукт', transcription: '[fruːt]' },
    { word: 'vegetable', translation: 'овощ', transcription: '[ˈvedʒtəbl]' },
    { word: 'rose', translation: 'роза', transcription: '[rəʊz]' },
    { word: 'tulip', translation: 'тюльпан', transcription: '[ˈtjuːlɪp]' },
    { word: 'daisy', translation: 'маргаритка', transcription: '[ˈdeɪzi]' },
    { word: 'sunflower', translation: 'подсолнух', transcription: '[ˈsʌnflaʊə]' },
    { word: 'oak', translation: 'дуб', transcription: '[əʊk]' },
    { word: 'pine', translation: 'сосна', transcription: '[paɪn]' },
    { word: 'birch', translation: 'берёза', transcription: '[bɜːtʃ]' },
    { word: 'bush', translation: 'куст', transcription: '[bʊʃ]' },
    { word: 'mushroom', translation: 'гриб', transcription: '[ˈmʌʃrʊm]' },
    { word: 'berry', translation: 'ягода', transcription: '[ˈberi]' },
    { word: 'nut', translation: 'орех', transcription: '[nʌt]' },
    { word: 'bamboo', translation: 'бамбук', transcription: '[ˌbæmˈbuː]' },
    { word: 'cactus', translation: 'кактус', transcription: '[ˈkæktəs]' },
  ],
  holidays: [
    { word: 'holiday', translation: 'праздник', transcription: '[ˈhɒlədeɪ]' },
    { word: 'birthday', translation: 'день рождения', transcription: '[ˈbɜːθdeɪ]' },
    { word: 'Christmas', translation: 'Рождество', transcription: '[ˈkrɪsməs]' },
    { word: 'New Year', translation: 'Новый год', transcription: '[njuː jɪə]' },
    { word: 'Easter', translation: 'Пасха', transcription: '[ˈiːstə]' },
    { word: 'wedding', translation: 'свадьба', transcription: '[ˈwedɪŋ]' },
    { word: 'anniversary', translation: 'годовщина', transcription: '[ˌænɪˈvɜːsəri]' },
    { word: 'party', translation: 'вечеринка', transcription: '[ˈpɑːti]' },
    { word: 'celebration', translation: 'празднование', transcription: '[ˌselɪˈbreɪʃən]' },
    { word: 'gift', translation: 'подарок', transcription: '[ɡɪft]' },
    { word: 'present', translation: 'подарок', transcription: '[ˈpreznt]' },
    { word: 'card', translation: 'открытка', transcription: '[kɑːd]' },
    { word: 'cake', translation: 'торт', transcription: '[keɪk]' },
    { word: 'candle', translation: 'свеча', transcription: '[ˈkændl]' },
    { word: 'balloon', translation: 'воздушный шар', transcription: '[bəˈluːn]' },
    { word: 'fireworks', translation: 'фейерверк', transcription: '[ˈfaɪəwɜːks]' },
    { word: 'decorations', translation: 'украшения', transcription: '[ˌdekəˈreɪʃənz]' },
    { word: 'guest', translation: 'гость', transcription: '[ɡest]' },
    { word: 'invitation', translation: 'приглашение', transcription: '[ˌɪnvɪˈteɪʃən]' },
    { word: 'toast', translation: 'тост', transcription: '[təʊst]' },
    { word: 'congratulations', translation: 'поздравления', transcription: '[kənˌɡrætʃʊˈleɪʃənz]' },
    { word: 'wish', translation: 'желание', transcription: '[wɪʃ]' },
  ],
  places: [
    { word: 'place', translation: 'место', transcription: '[pleɪs]' },
    { word: 'city', translation: 'город', transcription: '[ˈsɪti]' },
    { word: 'town', translation: 'городок', transcription: '[taʊn]' },
    { word: 'village', translation: 'деревня', transcription: '[ˈvɪlɪdʒ]' },
    { word: 'country', translation: 'страна', transcription: '[ˈkʌntri]' },
    { word: 'street', translation: 'улица', transcription: '[striːt]' },
    { word: 'square', translation: 'площадь', transcription: '[skweə]' },
    { word: 'park', translation: 'парк', transcription: '[pɑːk]' },
    { word: 'school', translation: 'школа', transcription: '[skuːl]' },
    { word: 'hospital', translation: 'больница', transcription: '[ˈhɒspɪtl]' },
    { word: 'shop', translation: 'магазин', transcription: '[ʃɒp]' },
    { word: 'restaurant', translation: 'ресторан', transcription: '[ˈrestrɒnt]' },
    { word: 'cafe', translation: 'кафе', transcription: '[ˈkæfeɪ]' },
    { word: 'library', translation: 'библиотека', transcription: '[ˈlaɪbrəri]' },
    { word: 'museum', translation: 'музей', transcription: '[mjuˈziːəm]' },
    { word: 'theater', translation: 'театр', transcription: '[ˈθɪətə]' },
    { word: 'cinema', translation: 'кинотеатр', transcription: '[ˈsɪnəmə]' },
    { word: 'church', translation: 'церковь', transcription: '[tʃɜːtʃ]' },
    { word: 'bank', translation: 'банк', transcription: '[bæŋk]' },
    { word: 'post office', translation: 'почта', transcription: '[pəʊst ˈɒfɪs]' },
    { word: 'station', translation: 'станция', transcription: '[ˈsteɪʃən]' },
    { word: 'airport', translation: 'аэропорт', transcription: '[ˈeəpɔːt]' },
  ],
  conjunctions: [
    { word: 'and', translation: 'и', transcription: '[ænd]' },
    { word: 'or', translation: 'или', transcription: '[ɔː]' },
    { word: 'but', translation: 'но', transcription: '[bʌt]' },
    { word: 'because', translation: 'потому что', transcription: '[bɪˈkɒz]' },
    { word: 'if', translation: 'если', transcription: '[ɪf]' },
    { word: 'when', translation: 'когда', transcription: '[wen]' },
    { word: 'while', translation: 'пока', transcription: '[waɪl]' },
    { word: 'although', translation: 'хотя', transcription: '[ɔːlˈðəʊ]' },
    { word: 'though', translation: 'хотя', transcription: '[ðəʊ]' },
    { word: 'since', translation: 'так как', transcription: '[sɪns]' },
    { word: 'until', translation: 'до тех пор пока', transcription: '[ənˈtɪl]' },
    { word: 'unless', translation: 'если не', transcription: '[ənˈles]' },
    { word: 'whether', translation: 'ли', transcription: '[ˈweðə]' },
    { word: 'that', translation: 'что', transcription: '[ðæt]' },
    { word: 'so', translation: 'так что', transcription: '[səʊ]' },
    { word: 'therefore', translation: 'поэтому', transcription: '[ˈðeəfɔː]' },
    { word: 'however', translation: 'однако', transcription: '[haʊˈevə]' },
    { word: 'moreover', translation: 'более того', transcription: '[mɔːˈrəʊvə]' },
    { word: 'furthermore', translation: 'более того', transcription: '[ˌfɜːðəˈmɔː]' },
    { word: 'nevertheless', translation: 'тем не менее', transcription: '[ˌnevəðəˈles]' },
    { word: 'meanwhile', translation: 'тем временем', transcription: '[ˈmiːnwaɪl]' },
    { word: 'besides', translation: 'кроме того', transcription: '[bɪˈsaɪdz]' },
  ],
  prepositions: [
    { word: 'in', translation: 'в', transcription: '[ɪn]' },
    { word: 'on', translation: 'на', transcription: '[ɒn]' },
    { word: 'at', translation: 'в, на', transcription: '[æt]' },
    { word: 'by', translation: 'к, у', transcription: '[baɪ]' },
    { word: 'with', translation: 'с', transcription: '[wɪð]' },
    { word: 'without', translation: 'без', transcription: '[wɪˈðaʊt]' },
    { word: 'for', translation: 'для', transcription: '[fɔː]' },
    { word: 'from', translation: 'из, от', transcription: '[frɒm]' },
    { word: 'to', translation: 'к, в', transcription: '[tuː]' },
    { word: 'of', translation: 'из, о', transcription: '[ɒv]' },
    { word: 'about', translation: 'о, вокруг', transcription: '[əˈbaʊt]' },
    { word: 'above', translation: 'над', transcription: '[əˈbʌv]' },
    { word: 'below', translation: 'под', transcription: '[bɪˈləʊ]' },
    { word: 'under', translation: 'под', transcription: '[ˈʌndə]' },
    { word: 'over', translation: 'над', transcription: '[ˈəʊvə]' },
    { word: 'between', translation: 'между', transcription: '[bɪˈtwiːn]' },
    { word: 'among', translation: 'среди', transcription: '[əˈmʌŋ]' },
    { word: 'through', translation: 'через', transcription: '[θruː]' },
    { word: 'during', translation: 'во время', transcription: '[ˈdjʊərɪŋ]' },
    { word: 'before', translation: 'до', transcription: '[bɪˈfɔː]' },
    { word: 'after', translation: 'после', transcription: '[ˈɑːftə]' },
    { word: 'towards', translation: 'к, по направлению к', transcription: '[təˈwɔːdz]' },
  ],
};
